/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from "workbox-precaching";
import { clientsClaim } from "workbox-core";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { NetworkFirst, CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

declare let self: ServiceWorkerGlobalScope;

// Clean old caches and claim clients immediately
cleanupOutdatedCaches();
self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// SPA Navigation Fallback - redirect all navigation requests to index.html
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  // Don't intercept API calls or static files
  denylist: [
    /^\/api\//,
    /\.[^/]+$/, // files with extensions
  ],
});
registerRoute(navigationRoute);

// Cache landing page - Network First (prioritize fresh content)
registerRoute(
  ({ url }) => url.pathname === "/" || url.pathname === "",
  new NetworkFirst({
    cacheName: "landing-page",
    networkTimeoutSeconds: 3,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60, // 1 hora
      }),
    ],
  })
);

// Cache admin pages - Network First (prioritize fresh content)
registerRoute(
  ({ url }) => url.pathname.startsWith("/admin"),
  new NetworkFirst({
    cacheName: "admin-pages",
    networkTimeoutSeconds: 3,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Cache chat pages - Network First (prioritize fresh content)
registerRoute(
  ({ url }) => url.pathname.startsWith("/chat"),
  new NetworkFirst({
    cacheName: "chat-pages",
    networkTimeoutSeconds: 3,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Cache images - Cache First (images don't change often)
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Message handler for skip waiting
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
